# Generated by Django 2.2 on 2020-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='Garage_Size',
            new_name='Garage_Capacity',
        ),
        migrations.RenameField(
            model_name='property_availability',
            old_name='Available',
            new_name='Availability_Comments',
        ),
        migrations.RenameField(
            model_name='property_availability',
            old_name='Availability_EndTime',
            new_name='EndTime',
        ),
        migrations.RenameField(
            model_name='property_availability',
            old_name='Availability_StartTime',
            new_name='StartTime',
        ),
        migrations.AddField(
            model_name='property_availability',
            name='IsAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
