# Generated by Django 2.2 on 2020-03-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0002_auto_20200320_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Property_Image',
            field=models.ImageField(default=1, upload_to='Images'),
            preserve_default=False,
        ),
    ]
