# Generated by Django 2.2 on 2020-03-26 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('airbnbapp', '0003_properties_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Available_Areas',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='properties',
            name='Property_Host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
