# Generated by Django 2.2 on 2020-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0004_auto_20200326_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Status',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
