# Generated by Django 2.2 on 2020-03-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0008_auto_20200330_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='Property_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
    ]
