# Generated by Django 2.2 on 2020-03-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0009_auto_20200330_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='County',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
