# Generated by Django 2.2 on 2020-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0010_properties_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='Adults',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='Children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
