# Generated by Django 2.2 on 2020-04-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbapp', '0011_auto_20200331_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='Property_Image',
            field=models.ImageField(default='Images/home1.jpg', upload_to='Images'),
        ),
    ]
